apiVersion: v1
kind: Pod
metadata:
  name: debezium-server
  labels:
    app: debezium-server
spec:
  containers:
    - name: debezium-server
      resources:
        requests:
          cpu: "250m"
          memory: "500Mi"
        limits:
          cpu: "250m"
          memory: "500Mi"
      image: docker.io/debezium/server:latest
      volumeMounts:
      - name: config-volume
        mountPath: /debezium/conf
  volumes:
    - name: config-volume
      configMap:
        name: debezium-config